// packages/react/src/Link.tsx
import React from 'react';
import { Icon } from './Icon';
import { getUrl, type Config, type StylingProps } from 'static-social-link';

export type LinkProps = React.DetailedHTMLProps<
	React.AnchorHTMLAttributes<HTMLAnchorElement>,
	HTMLAnchorElement
> &
	StylingProps & {
		config: Config;
		params: Record<string, string | undefined>;
		rel?: string;
		target?: string;
	};

export function Link({
	config,
	params,
	color,
	iconColor = 'white',
	size = 32,
	borderRadius = size * (6 / 32),
	round,
	rel = 'noreferrer noopener',
	target = '_blank',
	...props
}: LinkProps) {
	return (
		<a
			{...props}
			href={getUrl(config.url, params)}
			style={{
				display: 'inline-block',
				height: `${size}px`,
				borderRadius: round ? size / 2 : `${borderRadius}px`
			}}
			rel={rel}
			target={target}
			aria-label={`Share to ${config.name}`}
		>
			<Icon
				{...config}
				size={size}
				color={color || config.color}
				iconColor={iconColor === 'brand' ? config.color : iconColor}
				borderRadius={borderRadius}
				round={round}
			/>
		</a>
	);
}

// packages/svelte/src/lib/Link.svelte
<script lang="ts">
	import Icon from '$lib/Icon.svelte';
	import { getUrl, type Config } from 'static-social-link';

	export let config: Config;

	export let params: Record<string, string | undefined>;

	export let size = 32;
	export let color: string | undefined = undefined;
	export let iconColor = 'white';
	export let borderRadius: number | undefined = size * (6 / 32);
	export let round: boolean | undefined = undefined;

	export let rel = 'noreferrer noopener';
	export let target = '_blank';

	$: _color = color || config.color;
	$: _iconColor = iconColor === 'brand' ? config.color : iconColor;
</script>

<a
	href={getUrl(config.url, params)}
	style:height={`${size}px`}
	{rel}
	{target}
	aria-label={`Share to ${config.name}`}
	style:border-radius="{round ? size / 2 : borderRadius}px"
	{...$$restProps}
>
	<Icon {...config} {size} color={_color} iconColor={_iconColor} {borderRadius} {round} />
</a>

<style>
	a {
		display: inline-block;
	}
</style>
